version: 0.0
os: linux

files:
  - source: /
    destination: /opt/application
permissions:
  - object: /opt/application
    owner: ec2-user
    group: ec2-user
    mode: 755
hooks:
  AfterInstall:
    - location: deploy.sh
      timeout: 60
      runas: root