# This workflow will build a Java project with Gradle
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-gradle

on:
  push:
    branches: master

name: Deploy Spring boot to Amazon EC2
env:
  PROJECT_NAME: 서밑까제

jobs:
  build:
    name: DEPLOY
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2
    
    - name: Set up JDK 11
      uses: actions/setup-java@v1
      with:
        java-version: 11
    
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    
    - name: Build with Gradle
      run: ./gradlew build

    - name: Make zip file
      run: zip -qq -r ./$GITHUB_SHA.zip .
    
    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{secrets.ACCESS_KEY_ID}}
        aws-secret-access-key: ${{secrets.SECRET_ACCESS_KEY}}
        aws-region: ap-northeast-2
        
    - name: Upload to S3
      run: aws s3 cp --region ap-northeast-2 ./$GITHUB_SHA.zip s3://ksh-test/$PROJECT_NAME/$GITHUB_SHA.zip
    
    - name: Deploy Code
      run: aws deploy create-deployment --application-name ksh-test --deployment-config-name CodeDeployDefault.AllAtOnce --deployment-group-name ksh-test -s3-location bucket=ksh-test,bundleType=zip,key=$PROJECT_NAME/$GITHUB_SHA.zip
